# Generated by Django 2.1.5 on 2019-01-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores_banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='valorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_banco_brasil', models.BigIntegerField()),
                ('valor_banco_bradesco', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='valores_bancoModel',
        ),
    ]
